xTrain API: ModelRail::IUnifiedModelTrainListener Class Reference
ModelRail::IUnifiedModelTrainListener Class Reference
#include <xDuinoRails_xTrainAPI.h>
Public Member Functions
virtual ~IUnifiedModelTrainListener ()=default
virtual uint64_t getImplementedApi () const
Runtime check for implemented API features.
virtual void onLocoSpeedChange (const LocoHandle &loco, float speedPercent, Direction direction, int speedSteps)
Standard speed control (RCN-212).
virtual void onLocoFunctionChange (const LocoHandle &loco, int fIndex, bool isActive)
Binary function control (F0-F68+).
virtual void onLocoFunctionAnalogChange (const LocoHandle &loco, int fIndex, uint8_t value)
Analog function value (Pressure-sensitive / Analog features).
virtual void onLocoDispatchStateChange (const LocoHandle &loco, bool isAcquired, std::string ownerId)
Slot Management (LocoNet/XpressNet).
virtual void onConsistLink (const LocoHandle &master, const LocoHandle &slave, ConsistType type, bool inverted)
Consist Linking report.
virtual void onConsistUnlink (const LocoHandle &slave)
Dissolve a multi-traction link.
virtual void onTurnoutChange (uint16_t address, bool isThrown, bool isFeedback)
Standard Turnout (Binary).
virtual void onSignalAspectChange (uint16_t address, uint8_t aspectId, bool isFeedback)
Extended Signal Aspects (0-255).
virtual void onAccessoryAnalogValue (uint16_t address, float value0to1)
Direct analog control (Servos, Dimmers).
virtual void onAccessoryError (uint16_t address, uint8_t errorId, std::string errorMsg)
Hardware Diagnostic Error.
virtual void onSensorStateChange (uint32_t sensorId, bool isActive)
Occupancy / Feedback Sensors.
virtual void onTrackPowerChange (PowerState state)
Report global track power status change.
virtual void onFastClockUpdated (int64_t modelTimeUnix, float factor)
Model Time / Fast Clock (RCN-211).
virtual void onHardwareNodeAttached (std::string nodeUid, std::string productName, bool booster)
New Hardware Node Found (BiDiB / LNet).
virtual void onHardwareNodeLost (std::string nodeUid)
A hardware node has disconnected from the bus.
virtual void onSystemMessage (std::string source, std::string message)
Generic system message or log entry.
virtual void onLocoDetectedOnBlock (uint32_t sensorId, const LocoHandle &loco, DecoderOrientation orientation)
Train Location & Orientation Detection (RCN-217 Ch1).
virtual void onLocoTelemetryData (const LocoHandle &loco, TelemetryType type, float value)
Telemetry data from a locomotive (e.g., from RailCom Channel 2).
virtual void onLocoExternalStateChange (const LocoHandle &loco, ExternalState state)
External State Change (ABC / HLU). Loco stopped by track module despite throttle > 0. @CliLong <LOCO_EXTERNAL_STATE cab="123" state="PARKED">
virtual void onLocoRailComRawData (const LocoHandle &loco, uint8_t appId, const std::vector< uint8_t > &data)
Raw/Proprietary RailCom Data.
virtual void onNewLocoDiscovered (const LocoHandle &loco, const std::string &name, const std::string &icon)
Discovery (mfx / RailComPlus).
virtual void onCvRead (const LocoHandle &loco, int cvNumber)
A request to read a CV from a decoder has been issued.
virtual void onCvWrite (const LocoHandle &loco, int cvNumber, uint8_t value)
A request to write a CV to a decoder has been issued.
virtual void onCvReadDone (const LocoHandle &loco, int cvNumber, uint8_t value, bool success)
Result of a CV read operation.
virtual void onSusiConfigRead (const LocoHandle &loco, uint8_t bankIndex, uint8_t susiIndex, uint8_t value)
Result of reading a SUSI configuration register.
virtual void onConfigBlockLoad (const LocoHandle &loco, std::string domain, const std::vector< uint8_t > &data)
Mass Data Transfer.
virtual void onProgressUpdate (std::string operation, float percent)
Feedback on the progress of a long-running operation.
virtual void onLocoEventSync (const LocoHandle &loco, SyncType type, uint32_t value)
Triggered when a mechanical synchronization event occurs. Critical for "Puff-Chuff" sync (Steam) or Gear Changes (Diesel).
Detailed Description
Definition at line 177 of file xDuinoRails_xTrainAPI.h.
Constructor & Destructor Documentation
~IUnifiedModelTrainListener()
virtual ModelRail::IUnifiedModelTrainListener::~IUnifiedModelTrainListener () virtual default
Member Function Documentation
getImplementedApi()
virtual uint64_t ModelRail::IUnifiedModelTrainListener::getImplementedApi () const inline virtual
Runtime check for implemented API features.
Returns
A bitmask of ApiFeature flags indicating which functions are implemented.
Reimplemented in ModelRail::CmdLinePrinter, and ModelRail::XmlPrinter.
Definition at line 185 of file xDuinoRails_xTrainAPI.h.
onAccessoryAnalogValue()
virtual void ModelRail::IUnifiedModelTrainListener::onAccessoryAnalogValue (uint16_t address, float value0to1) inline virtual
Direct analog control (Servos, Dimmers).
Parameters
value0to1 Normalized float (0.0 - 1.0). @CliLong <ACCESSORY_ANALOG address="789" value="0.75">
Reimplemented in ModelRail::CmdLinePrinter, and ModelRail::XmlPrinter.
Definition at line 267 of file xDuinoRails_xTrainAPI.h.
Referenced by ModelRail::CmdLineParser::parse().
onAccessoryError()
virtual void ModelRail::IUnifiedModelTrainListener::onAccessoryError (uint16_t address, uint8_t errorId, std::string errorMsg) inline virtual
Hardware Diagnostic Error.
Parameters
errorId 1=OpenLoad, 2=Short, 3=Stall. @CliLong <ACCESSORY_ERROR address="789" errorId="1" errorMessage="Overload">
Reimplemented in ModelRail::CmdLinePrinter, and ModelRail::XmlPrinter.
Definition at line 274 of file xDuinoRails_xTrainAPI.h.
Referenced by ModelRail::CmdLineParser::parse().
onConfigBlockLoad()
virtual void ModelRail::IUnifiedModelTrainListener::onConfigBlockLoad (const LocoHandle & loco, std::string domain, const std::vector< uint8_t > & data) inline virtual
Mass Data Transfer.
Parameters
domain Data type (e.g., "ICON", "MFX_CONFIG"). @CliLong <CONFIG_BLOCK_LOADED cab="123" domain="sound" data="DEADBEEF">
Reimplemented in ModelRail::CmdLinePrinter, and ModelRail::XmlPrinter.
Definition at line 416 of file xDuinoRails_xTrainAPI.h.
onConsistLink()
virtual void ModelRail::IUnifiedModelTrainListener::onConsistLink (const LocoHandle & master, const LocoHandle & slave, ConsistType type, bool inverted) inline virtual
Consist Linking report.
Parameters
type Linking method (CV19 vs Software).
inverted True if slave is reversed relative to master. @CliLong <CONSIST_LINK master="123" slave="456" type="ADVANCED" inverted="false">
Reimplemented in ModelRail::CmdLinePrinter, and ModelRail::XmlPrinter.
Definition at line 232 of file xDuinoRails_xTrainAPI.h.
Referenced by ModelRail::CmdLineParser::parse().
onConsistUnlink()
virtual void ModelRail::IUnifiedModelTrainListener::onConsistUnlink (const LocoHandle & slave) inline virtual
Dissolve a multi-traction link.
Parameters
slave The locomotive being removed from the consist. @CliLong <CONSIST_UNLINK slave="456">
Reimplemented in ModelRail::CmdLinePrinter, and ModelRail::XmlPrinter.
Definition at line 239 of file xDuinoRails_xTrainAPI.h.
Referenced by ModelRail::CmdLineParser::parse().
onCvRead()
virtual void ModelRail::IUnifiedModelTrainListener::onCvRead (const LocoHandle & loco, int cvNumber) inline virtual
A request to read a CV from a decoder has been issued.
Parameters
loco The target locomotive.
cvNumber The Configuration Variable number to read. @CliShort <R cv track> @CliLong <READ_CV cv="1" track="1">
Reimplemented in ModelRail::CmdLinePrinter, and ModelRail::XmlPrinter.
Definition at line 378 of file xDuinoRails_xTrainAPI.h.
onCvReadDone()
virtual void ModelRail::IUnifiedModelTrainListener::onCvReadDone (const LocoHandle & loco, int cvNumber, uint8_t value, bool success) inline virtual
Result of a CV read operation.
Parameters
loco The target locomotive.
cvNumber The CV that was read.
value The 8-bit value returned by the decoder.
success True if the read was successful (acknowledged). @CliShort r <cv> <value> @CliLong <CV_READ_RESULT cab="123" cv="1" value="10" success="true">
Reimplemented in ModelRail::CmdLinePrinter, and ModelRail::XmlPrinter.
Definition at line 399 of file xDuinoRails_xTrainAPI.h.
onCvWrite()
virtual void ModelRail::IUnifiedModelTrainListener::onCvWrite (const LocoHandle & loco, int cvNumber, uint8_t value) inline virtual
A request to write a CV to a decoder has been issued.
Parameters
loco The target locomotive.
cvNumber The Configuration Variable number to write.
value The 8-bit value to write. @CliShort <W cv value track> @CliLong <WRITE_CV_BYTE cv="1" value="123" track="1">
Reimplemented in ModelRail::CmdLinePrinter, and ModelRail::XmlPrinter.
Definition at line 388 of file xDuinoRails_xTrainAPI.h.
onFastClockUpdated()
virtual void ModelRail::IUnifiedModelTrainListener::onFastClockUpdated (int64_t modelTimeUnix, float factor) inline virtual
Model Time / Fast Clock (RCN-211).
Parameters
modelTimeUnix Unix Timestamp (int64).
factor Acceleration factor. @CliLong <FAST_CLOCK time="1678886400" factor="4.0">
Reimplemented in ModelRail::CmdLinePrinter, and ModelRail::XmlPrinter.
Definition at line 303 of file xDuinoRails_xTrainAPI.h.
Referenced by ModelRail::CmdLineParser::parse().
onHardwareNodeAttached()
virtual void ModelRail::IUnifiedModelTrainListener::onHardwareNodeAttached (std::string nodeUid, std::string productName, bool booster) inline virtual
New Hardware Node Found (BiDiB / LNet).
Parameters
booster True if node supplies power. @CliLong <HARDWARE_NODE_ATTACHED uid="abc-123" productName="xPressNet" booster="false">
Reimplemented in ModelRail::CmdLinePrinter, and ModelRail::XmlPrinter.
Definition at line 310 of file xDuinoRails_xTrainAPI.h.
Referenced by ModelRail::CmdLineParser::parse().
onHardwareNodeLost()
virtual void ModelRail::IUnifiedModelTrainListener::onHardwareNodeLost (std::string nodeUid) inline virtual
A hardware node has disconnected from the bus.
Parameters
nodeUid Unique identifier of the lost node. @CliLong <HARDWARE_NODE_LOST uid="abc-123">
Reimplemented in ModelRail::CmdLinePrinter, and ModelRail::XmlPrinter.
Definition at line 317 of file xDuinoRails_xTrainAPI.h.
Referenced by ModelRail::CmdLineParser::parse().
onLocoDetectedOnBlock()
virtual void ModelRail::IUnifiedModelTrainListener::onLocoDetectedOnBlock (uint32_t sensorId, const LocoHandle & loco, DecoderOrientation orientation) inline virtual
Train Location & Orientation Detection (RCN-217 Ch1).
Parameters
orientation Chimney vs Tender first. @CliLong <LOCO_DETECTED_ON_BLOCK sensorId="202" cab="123" orientation="FORWARD">
Reimplemented in ModelRail::CmdLinePrinter, and ModelRail::XmlPrinter.
Definition at line 336 of file xDuinoRails_xTrainAPI.h.
Referenced by ModelRail::CmdLineParser::parse().
onLocoDispatchStateChange()
virtual void ModelRail::IUnifiedModelTrainListener::onLocoDispatchStateChange (const LocoHandle & loco, bool isAcquired, std::string ownerId) inline virtual
Slot Management (LocoNet/XpressNet).
Parameters
isAcquired True=Controlled by throttle, False=Released.
ownerId ID of the controlling device. @CliLong <DISPATCH cab="123" state="ACQUIRED" owner="user1">
Reimplemented in ModelRail::CmdLinePrinter, and ModelRail::XmlPrinter.
Definition at line 224 of file xDuinoRails_xTrainAPI.h.
Referenced by ModelRail::CmdLineParser::parse().
onLocoEventSync()
virtual void ModelRail::IUnifiedModelTrainListener::onLocoEventSync (const LocoHandle & loco, SyncType type, uint32_t value) inline virtual
Triggered when a mechanical synchronization event occurs. Critical for "Puff-Chuff" sync (Steam) or Gear Changes (Diesel).
Parameters
loco The locomotive handle.
type The type of mechanical event (e.g., CAM_PULSE).
value An optional value (e.g., new gear number). @CliLong <MECHANICAL_SYNC_EVENT cab="123" type="CHUFF" value="1">
Reimplemented in ModelRail::CmdLinePrinter, and ModelRail::XmlPrinter.
Definition at line 438 of file xDuinoRails_xTrainAPI.h.
Referenced by ModelRail::CmdLineParser::parse().
onLocoExternalStateChange()
virtual void ModelRail::IUnifiedModelTrainListener::onLocoExternalStateChange (const LocoHandle & loco, ExternalState state) inline virtual
External State Change (ABC / HLU). Loco stopped by track module despite throttle > 0. @CliLong <LOCO_EXTERNAL_STATE cab="123" state="PARKED">
Reimplemented in ModelRail::CmdLinePrinter, and ModelRail::XmlPrinter.
Definition at line 351 of file xDuinoRails_xTrainAPI.h.
onLocoFunctionAnalogChange()
virtual void ModelRail::IUnifiedModelTrainListener::onLocoFunctionAnalogChange (const LocoHandle & loco, int fIndex, uint8_t value) inline virtual
Analog function value (Pressure-sensitive / Analog features).
Parameters
value Analog value (0-255). @CliLong <LOCO_FUNCTION_ANALOG cab="123" function="8" value="255">
Reimplemented in ModelRail::CmdLinePrinter, and ModelRail::XmlPrinter.
Definition at line 216 of file xDuinoRails_xTrainAPI.h.
onLocoFunctionChange()
virtual void ModelRail::IUnifiedModelTrainListener::onLocoFunctionChange (const LocoHandle & loco, int fIndex, bool isActive) inline virtual
Binary function control (F0-F68+).
Parameters
fIndex Function index (0=Light, 1=F1...).
isActive True=ON, False=OFF. @CliShort <f cab f_num state> @CliLong <FUNCTION cab="123" function="1" state="1">
Reimplemented in ModelRail::CmdLinePrinter, and ModelRail::XmlPrinter.
Definition at line 209 of file xDuinoRails_xTrainAPI.h.
Referenced by ModelRail::CmdLineParser::parse().
onLocoRailComRawData()
virtual void ModelRail::IUnifiedModelTrainListener::onLocoRailComRawData (const LocoHandle & loco, uint8_t appId, const std::vector< uint8_t > & data) inline virtual
Raw/Proprietary RailCom Data.
Parameters
appId RailCom Application ID. @CliLong <LOCO_RAILCOM_RAW cab="123" appId="1" data="A0B1C2">
Reimplemented in ModelRail::CmdLinePrinter, and ModelRail::XmlPrinter.
Definition at line 358 of file xDuinoRails_xTrainAPI.h.
onLocoSpeedChange()
virtual void ModelRail::IUnifiedModelTrainListener::onLocoSpeedChange (const LocoHandle & loco, float speedPercent, Direction direction, int speedSteps) inline virtual
Standard speed control (RCN-212).
Parameters
loco Target locomotive.
speedPercent 0.0f (Stop) to 100.0f (Max).
direction Requested direction.
speedSteps Step mode (14, 28, 128). @CliShort <t cab speed dir steps> @CliLong <THROTTLE cab="123" speed="100" direction="1" steps="128">
Reimplemented in ModelRail::CmdLinePrinter, and ModelRail::XmlPrinter.
Definition at line 200 of file xDuinoRails_xTrainAPI.h.
Referenced by ModelRail::CmdLineParser::parse().
onLocoTelemetryData()
virtual void ModelRail::IUnifiedModelTrainListener::onLocoTelemetryData (const LocoHandle & loco, TelemetryType type, float value) inline virtual
Telemetry data from a locomotive (e.g., from RailCom Channel 2).
Parameters
type The type of data being reported (e.g., speed, load).
value The actual telemetry value. @CliLong <LOCO_TELEMETRY cab="123" type="SPEED" value="50.5">
Reimplemented in ModelRail::CmdLinePrinter, and ModelRail::XmlPrinter.
Definition at line 344 of file xDuinoRails_xTrainAPI.h.
Referenced by ModelRail::CmdLineParser::parse().
onNewLocoDiscovered()
virtual void ModelRail::IUnifiedModelTrainListener::onNewLocoDiscovered (const LocoHandle & loco, const std::string & name, const std::string & icon) inline virtual
Discovery (mfx / RailComPlus).
Parameters
icon Suggested icon filename. @CliLong <NEW_LOCO_DISCOVERED cab="123" name="Big Boy" icon="steam_loco.png">
Reimplemented in ModelRail::CmdLinePrinter, and ModelRail::XmlPrinter.
Definition at line 365 of file xDuinoRails_xTrainAPI.h.
onProgressUpdate()
virtual void ModelRail::IUnifiedModelTrainListener::onProgressUpdate (std::string operation, float percent) inline virtual
Feedback on the progress of a long-running operation.
Parameters
operation A string identifying the task (e.g., "CV_READ_ALL", "FIRMWARE_UPDATE").
percent The progress from 0.0 to 100.0. @CliLong <PROGRESS_UPDATE operation="Firmware Update" percent="75.5">
Reimplemented in ModelRail::CmdLinePrinter, and ModelRail::XmlPrinter.
Definition at line 424 of file xDuinoRails_xTrainAPI.h.
onSensorStateChange()
virtual void ModelRail::IUnifiedModelTrainListener::onSensorStateChange (uint32_t sensorId, bool isActive) inline virtual
Occupancy / Feedback Sensors.
Parameters
sensorId Unique 32-bit ID.
isActive True=Occupied. @CliShort <Y id state> @CliLong <SENSOR id="101" state="ACTIVE">
Reimplemented in ModelRail::CmdLinePrinter, and ModelRail::XmlPrinter.
Definition at line 283 of file xDuinoRails_xTrainAPI.h.
Referenced by ModelRail::CmdLineParser::parse().
onSignalAspectChange()
virtual void ModelRail::IUnifiedModelTrainListener::onSignalAspectChange (uint16_t address, uint8_t aspectId, bool isFeedback) inline virtual
Extended Signal Aspects (0-255).
Parameters
aspectId Aspect ID (Hp0, Hp1, etc.). @CliShort <Q id state> @CliLong <ACCESSORY id="789" state="1">
Reimplemented in ModelRail::CmdLinePrinter, and ModelRail::XmlPrinter.
Definition at line 260 of file xDuinoRails_xTrainAPI.h.
Referenced by ModelRail::CmdLineParser::parse().
onSusiConfigRead()
virtual void ModelRail::IUnifiedModelTrainListener::onSusiConfigRead (const LocoHandle & loco, uint8_t bankIndex, uint8_t susiIndex, uint8_t value) inline virtual
Result of reading a SUSI configuration register.
Parameters
loco The target locomotive.
bankIndex The memory bank (e.g., for different sound profiles).
susiIndex The specific SUSI register index.
value The value read from the register. @CliLong <SUSI_CONFIG_READ cab="123" bank="1" index="2" value="3">
Reimplemented in ModelRail::CmdLinePrinter, and ModelRail::XmlPrinter.
Definition at line 409 of file xDuinoRails_xTrainAPI.h.
onSystemMessage()
virtual void ModelRail::IUnifiedModelTrainListener::onSystemMessage (std::string source, std::string message) inline virtual
Generic system message or log entry.
Parameters
source The component originating the message (e.g., "PowerManager", "BiDiB-Stack").
message The content of the message. @CliLong <SYSTEM_MESSAGE source="WebServer" message="User logged in">
Reimplemented in ModelRail::CmdLinePrinter, and ModelRail::XmlPrinter.
Definition at line 325 of file xDuinoRails_xTrainAPI.h.
Referenced by ModelRail::CmdLineParser::parse().
onTrackPowerChange()
virtual void ModelRail::IUnifiedModelTrainListener::onTrackPowerChange (PowerState state) inline virtual
Report global track power status change.
Parameters
state The new power state (ON, OFF, EMERGENCY_STOP). @CliShort <1> / <0> @CliLong <POWER state="ON">
Reimplemented in ModelRail::CmdLinePrinter, and ModelRail::XmlPrinter.
Definition at line 295 of file xDuinoRails_xTrainAPI.h.
Referenced by ModelRail::CmdLineParser::parse().
onTurnoutChange()
virtual void ModelRail::IUnifiedModelTrainListener::onTurnoutChange (uint16_t address, bool isThrown, bool isFeedback) inline virtual
Standard Turnout (Binary).
Parameters
isThrown True=Diverging, False=Straight.
isFeedback True=Real hardware confirmation. @CliShort <T id state> @CliLong <TURNOUT id="456" state="1">
Reimplemented in ModelRail::CmdLinePrinter, and ModelRail::XmlPrinter.
Definition at line 252 of file xDuinoRails_xTrainAPI.h.
Referenced by ModelRail::CmdLineParser::parse().
The documentation for this class was generated from the following file:
src/xDuinoRails_xTrainAPI.h