xTrain API: ModelRail::CmdLineParser Class Reference
ModelRail::CmdLineParser Class Reference
#include <xDuinoRails_xTrainAPI_utils.h>
Public Member Functions
CmdLineParser (IUnifiedModelTrainListener &listener)
String getParamValue (const String &params, const char *key)
void parse (const String &command)
Detailed Description
Definition at line 1081 of file xDuinoRails_xTrainAPI_utils.h.
Constructor & Destructor Documentation
CmdLineParser()
ModelRail::CmdLineParser::CmdLineParser (IUnifiedModelTrainListener & listener) inline
Definition at line 1083 of file xDuinoRails_xTrainAPI_utils.h.
Member Function Documentation
getParamValue()
String ModelRail::CmdLineParser::getParamValue (const String & params, const char * key) inline
Definition at line 1085 of file xDuinoRails_xTrainAPI_utils.h.
Referenced by parse().
parse()
void ModelRail::CmdLineParser::parse (const String & command) inline
Definition at line 1099 of file xDuinoRails_xTrainAPI_utils.h.
References ModelRail::ADVANCED_DCC, ModelRail::BRAKE_SQUEAL_START, ModelRail::CAM_PULSE, ModelRail::CYLINDER_CYCLE, ModelRail::DCC, ModelRail::DOOR_MOVEMENT, ModelRail::GEAR_CHANGE_DOWN, ModelRail::GEAR_CHANGE_UP, getParamValue(), ModelRail::INVERTED, ModelRail::MU_LOCONET, ModelRail::NORMAL, ModelRail::OFF, ModelRail::ON, ModelRail::IUnifiedModelTrainListener::onAccessoryAnalogValue(), ModelRail::IUnifiedModelTrainListener::onAccessoryError(), ModelRail::IUnifiedModelTrainListener::onConsistLink(), ModelRail::IUnifiedModelTrainListener::onConsistUnlink(), ModelRail::IUnifiedModelTrainListener::onFastClockUpdated(), ModelRail::IUnifiedModelTrainListener::onHardwareNodeAttached(), ModelRail::IUnifiedModelTrainListener::onHardwareNodeLost(), ModelRail::IUnifiedModelTrainListener::onLocoDetectedOnBlock(), ModelRail::IUnifiedModelTrainListener::onLocoDispatchStateChange(), ModelRail::IUnifiedModelTrainListener::onLocoEventSync(), ModelRail::IUnifiedModelTrainListener::onLocoFunctionChange(), ModelRail::IUnifiedModelTrainListener::onLocoSpeedChange(), ModelRail::IUnifiedModelTrainListener::onLocoTelemetryData(), ModelRail::IUnifiedModelTrainListener::onSensorStateChange(), ModelRail::IUnifiedModelTrainListener::onSignalAspectChange(), ModelRail::IUnifiedModelTrainListener::onSystemMessage(), ModelRail::IUnifiedModelTrainListener::onTrackPowerChange(), ModelRail::IUnifiedModelTrainListener::onTurnoutChange(), ModelRail::SPEED_KMH, ModelRail::UNIVERSAL_HOST, and ModelRail::UNKNOWN.
The documentation for this class was generated from the following file:
src/xDuinoRails_xTrainAPI_utils.h