xTrain API: ModelRail Namespace Reference
ModelRail Namespace Reference
Classes
class CmdLineParser
class CmdLinePrinter
class IUnifiedModelTrainListener
struct LocoHandle
Core Identifier for a Locomotive.
class XmlParser
class XmlPrinter
Enumerations
enum class Protocol : uint8_t {
DCC , MM_I , MM_II , MFX ,
SELECTRIX , SX2 , LOCONET , BIDIB ,
XPRESSNET , CAN_GENERIC
}
List of supported digital protocols. See NMRA, RCN, and Manufacturer specs for details.
enum class Direction : uint8_t { REVERSE = 0 , FORWARD = 1 , UNKNOWN = 2 }
Logical driving direction.
enum class PowerState : uint8_t { OFF = 0 , ON = 1 , EMERGENCY_STOP = 2 , SHORT_CIRCUIT = 3 }
Global track power status.
enum class DecoderOrientation : uint8_t { NORMAL = 0 , INVERTED = 1 , UNKNOWN = 2 }
Physical orientation of the decoder on the track (RCN-217).
enum class ExternalState : uint8_t {
FREE_RUN = 0 , STOPPED_BY_ABC_SIGNAL = 1 , STOPPED_BY_DC_BRAKE = 2 , STOPPED_BY_HLU = 3 ,
RESTRICTED_SPEED_HLU = 4
}
External influence on movement (ABC, HLU, etc.).
enum class TelemetryType : uint8_t {
SPEED_KMH , LOAD_PERCENT , VOLTAGE_TRACK , CURRENT_AMP ,
FUEL_LEVEL , TEMP_CELSIUS , QOS_ERROR_RATE , ODOMETER_VALUE ,
POSITION_CONFIDENCE
}
Telemetry data types (RailCom Ch2 / BiDiB).
enum class SyncType : uint8_t {
CAM_PULSE , CYLINDER_CYCLE , GEAR_CHANGE_UP , GEAR_CHANGE_DOWN ,
BRAKE_SQUEAL_START , DOOR_MOVEMENT
}
Types of hardware/mechanical sync events. Used to couple mechanical movement (Motor/Wheels) with Acoustics (Sound) or Effects.
enum class ConsistType : uint8_t { ADVANCED_DCC , UNIVERSAL_HOST , MU_LOCONET }
Linking method for multi-traction.
enum class ApiFeature : uint64_t {
onLocoSpeedChange = 1ULL << 0 , onLocoFunctionChange = 1ULL << 1 , onLocoFunctionAnalogChange = 1ULL << 2 , onLocoDispatchStateChange = 1ULL << 3 ,
onConsistLink = 1ULL << 4 , onConsistUnlink = 1ULL << 5 , onTurnoutChange = 1ULL << 6 , onSignalAspectChange = 1ULL << 7 ,
onAccessoryAnalogValue = 1ULL << 8 , onAccessoryError = 1ULL << 9 , onSensorStateChange = 1ULL << 10 , onTrackPowerChange = 1ULL << 11 ,
onFastClockUpdated = 1ULL << 12 , onHardwareNodeAttached = 1ULL << 13 , onHardwareNodeLost = 1ULL << 14 , onSystemMessage = 1ULL << 15 ,
onLocoDetectedOnBlock = 1ULL << 16 , onLocoTelemetryData = 1ULL << 17 , onLocoExternalStateChange = 1ULL << 18 , onLocoRailComRawData = 1ULL << 19 ,
onNewLocoDiscovered = 1ULL << 20 , onCvRead = 1ULL << 21 , onCvWrite = 1ULL << 22 , onCvReadDone = 1ULL << 23 ,
onSusiConfigRead = 1ULL << 24 , onConfigBlockLoad = 1ULL << 25 , onProgressUpdate = 1ULL << 26 , onLocoEventSync = 1ULL << 27 ,
ALL_TRAFFIC_DISPATCHING , ALL_INFRASTRUCTURE , ALL_SYSTEM_TOPOLOGY , ALL_TELEMETRY_ID ,
ALL_CONFIGURATION , ALL_SYNC = onLocoEventSync , ALL_FEATURES
}
Bitmask for self-inspection of implemented API features. Allows a class to declare which specific functions of the IUnifiedModelTrainListener interface it implements.
Functions
static std::vector< uint8_t > hexToBytes (const std::string &hex)
static void printHex (Stream *stream, const std::vector< uint8_t > &data)
Enumeration Type Documentation
ApiFeature
enum class ModelRail::ApiFeature : uint64_t strong
Bitmask for self-inspection of implemented API features. Allows a class to declare which specific functions of the IUnifiedModelTrainListener interface it implements.
Enumerator
onLocoSpeedChange
onLocoFunctionChange
onLocoFunctionAnalogChange
onLocoDispatchStateChange
onConsistLink
onConsistUnlink
onTurnoutChange
onSignalAspectChange
onAccessoryAnalogValue
onAccessoryError
onSensorStateChange
onTrackPowerChange
onFastClockUpdated
onHardwareNodeAttached
onHardwareNodeLost
onSystemMessage
onLocoDetectedOnBlock
onLocoTelemetryData
onLocoExternalStateChange
onLocoRailComRawData
onNewLocoDiscovered
onCvRead
onCvWrite
onCvReadDone
onSusiConfigRead
onConfigBlockLoad
onProgressUpdate
onLocoEventSync
ALL_TRAFFIC_DISPATCHING
ALL_INFRASTRUCTURE
ALL_SYSTEM_TOPOLOGY
ALL_TELEMETRY_ID
ALL_CONFIGURATION
ALL_SYNC
ALL_FEATURES
Definition at line 125 of file xDuinoRails_xTrainAPI.h.
ConsistType
enum class ModelRail::ConsistType : uint8_t strong
Linking method for multi-traction.
Enumerator
ADVANCED_DCC
Decoder-based (CV19).
UNIVERSAL_HOST
Software-based (Command Station manages commands).
MU_LOCONET
LocoNet specific slot linking.
Definition at line 103 of file xDuinoRails_xTrainAPI.h.
DecoderOrientation
enum class ModelRail::DecoderOrientation : uint8_t strong
Physical orientation of the decoder on the track (RCN-217).
Enumerator
NORMAL
Decoder "Forward" matches Track "Positive" (Chimney first).
INVERTED
Decoder "Forward" matches Track "Negative" (Tender first).
UNKNOWN
Orientation detection failed.
Definition at line 58 of file xDuinoRails_xTrainAPI.h.
Direction
enum class ModelRail::Direction : uint8_t strong
Logical driving direction.
Enumerator
REVERSE
Backward movement.
FORWARD
Forward movement.
UNKNOWN
State is undetermined.
Definition at line 41 of file xDuinoRails_xTrainAPI.h.
ExternalState
enum class ModelRail::ExternalState : uint8_t strong
External influence on movement (ABC, HLU, etc.).
Enumerator
FREE_RUN
No restrictions.
STOPPED_BY_ABC_SIGNAL
Stopped by Lenz ABC Asymmetry.
STOPPED_BY_DC_BRAKE
Stopped by Marklin DC Brake Module.
STOPPED_BY_HLU
Stopped by Zimo HLU signal.
RESTRICTED_SPEED_HLU
Speed limit enforced by Zimo HLU.
Definition at line 65 of file xDuinoRails_xTrainAPI.h.
PowerState
enum class ModelRail::PowerState : uint8_t strong
Global track power status.
Enumerator
OFF
System idle / No power to tracks.
ON
Normal operation.
EMERGENCY_STOP
Logical stop (broadcast speed 0), power may remain.
SHORT_CIRCUIT
Hardware trip / Power cut.
Definition at line 48 of file xDuinoRails_xTrainAPI.h.
Protocol
enum class ModelRail::Protocol : uint8_t strong
List of supported digital protocols. See NMRA, RCN, and Manufacturer specs for details.
Enumerator
DCC
NMRA DCC (S-9.1, S-9.2, RCN-210). Worldwide standard.
MM_I
Marklin Motorola I (Old). Register mode, 14 steps, unidirectional.
MM_II
Marklin Motorola II (New). Adds direction and functions F1-F4.
MFX
mfx / M4. Bidirectional, auto-registration (UID), 128 steps.
SELECTRIX
Selectrix (SX1). Synchronous bus (NEM 680/681).
SX2
Selectrix 2 (SX2). RCN extension for multiprotocol & config.
LOCONET
Digitrax LocoNet. Peer-to-Peer, OpCode based.
BIDIB
BiDiB. High-speed, tree-topology, CRC protected.
XPRESSNET
Lenz XpressNet. RS-485 Master-Slave.
CAN_GENERIC
Generic CAN (e.g., OpenLCB/LCC or Marklin CS2/CS3).
Definition at line 25 of file xDuinoRails_xTrainAPI.h.
SyncType
enum class ModelRail::SyncType : uint8_t strong
Types of hardware/mechanical sync events. Used to couple mechanical movement (Motor/Wheels) with Acoustics (Sound) or Effects.
Enumerator
CAM_PULSE
Wheel rotation pulse (e.g., for steam chuff generation).
CYLINDER_CYCLE
Full cylinder cycle completed.
GEAR_CHANGE_UP
Gearbox shifted up (for diesel/hydraulic transmission).
GEAR_CHANGE_DOWN
Gearbox shifted down.
BRAKE_SQUEAL_START
Mechanical brake engaged (triggers squeal sound).
DOOR_MOVEMENT
Door opening/closing detected.
Definition at line 91 of file xDuinoRails_xTrainAPI.h.
TelemetryType
enum class ModelRail::TelemetryType : uint8_t strong
Telemetry data types (RailCom Ch2 / BiDiB).
Enumerator
SPEED_KMH
Actual measured speed (km/h).
LOAD_PERCENT
Motor load (0-100%).
VOLTAGE_TRACK
Decoder input voltage (V).
CURRENT_AMP
Motor current (A).
FUEL_LEVEL
Simulated supply level (Coal/Water/Diesel %).
TEMP_CELSIUS
Internal temperature (C).
QOS_ERROR_RATE
Packet error rate / QoS.
ODOMETER_VALUE
Total distance travelled (cm/m).
POSITION_CONFIDENCE
Localization confidence (0-100%).
Definition at line 74 of file xDuinoRails_xTrainAPI.h.
Function Documentation
hexToBytes()
static std::vector< uint8_t > ModelRail::hexToBytes (const std::string & hex) static
Definition at line 16 of file xDuinoRails_xTrainAPI_utils.h.
printHex()
static void ModelRail::printHex (Stream * stream, const std::vector< uint8_t > & data) static
Definition at line 27 of file xDuinoRails_xTrainAPI_utils.h.
Referenced by ModelRail::CmdLinePrinter::onConfigBlockLoad(), ModelRail::XmlPrinter::onConfigBlockLoad(), ModelRail::CmdLinePrinter::onLocoRailComRawData(), and ModelRail::XmlPrinter::onLocoRailComRawData().