xTrain API: lib/yxml/yxml.h File Reference
yxml.h File Reference
#include <stddef.h>
#include <stdint.h>
Classes
struct yxml_t
Enumerations
enum yxml_ret_t {
YXML_OK = 0 , YXML_ELEMSTART , YXML_ELEMEND , YXML_ATTRSTART ,
YXML_ATTRVAL , YXML_ATTREND , YXML_CONTENT , YXML_PISTART ,
YXML_PICONTENT , YXML_PIEND , YXML_EREF = -1 , YXML_ECLOSE = -2 ,
YXML_ESTACK = -3 , YXML_ESYN = -4 , YXML_EEOF = -5
}
Functions
void yxml_init (yxml_t *x, void *stack, size_t stacksize)
yxml_ret_t yxml_parse (yxml_t *x, int ch)
yxml_ret_t yxml_eof (yxml_t *x)
size_t yxml_symlen (yxml_t *x, const char *s)
Enumeration Type Documentation
yxml_ret_t
enum yxml_ret_t
Enumerator
YXML_OK
YXML_ELEMSTART
YXML_ELEMEND
YXML_ATTRSTART
YXML_ATTRVAL
YXML_ATTREND
YXML_CONTENT
YXML_PISTART
YXML_PICONTENT
YXML_PIEND
YXML_EREF
YXML_ECLOSE
YXML_ESTACK
YXML_ESYN
YXML_EEOF
Definition at line 33 of file yxml.h.
Function Documentation
yxml_eof()
yxml_ret_t yxml_eof (yxml_t * x)
Referenced by ModelRail::XmlParser::parse().
yxml_init()
void yxml_init (yxml_t * x, void * stack, size_t stacksize)
Referenced by ModelRail::XmlParser::XmlParser().
yxml_parse()
yxml_ret_t yxml_parse (yxml_t * x, int ch)
Referenced by ModelRail::XmlParser::parse().
yxml_symlen()
size_t yxml_symlen (yxml_t * x, const char * s)